site_name: KMaP
site_url: https://kmap.rafambn.com
site_description: Flexible and powerful mapping library for Compose Multiplatform
repo_name: rafambn/KMaP
repo_url: https://github.com/rafambn/KMaP

theme:
  name: material
  logo: 'assets/KMaP-Logo.svg'
  favicon: 'assets/KMaP-Logo.svg'
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - content.code.annotate
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'orange'
      accent: 'deep-purple'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'deep-purple'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - toc:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - admonition

nav:
  - Overview: index.md
  - Setup: setup.md
  - Usage: usage.md
  - Upcoming: upcoming.md